# Render Blueprint for AI Registration Assistant
# Reference: https://render.com/docs/blueprint-spec

# Backend service
services:
  - type: web
    name: ai-registration-backend
    env: python
    build:
      dockerfile: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-registration-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"  # 24 hours
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "*"  # In production, replace with your frontend URL
    plan: free
    numInstances: 1
    buildCommand: |
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    healthCheckPath: /health
    autoDeploy: yes

# PostgreSQL database
databases:
  - name: ai-registration-db
    databaseName: ai_registration
    user: postgres
    plan: free  # For production, consider using a paid plan
    ipAllowList:
      - 0.0.0.0/0  # Restrict this in production

# Frontend (deployed to Vercel)
# Note: The frontend should be deployed separately to Vercel
# and configured to use the backend URL from the service above
